---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: openshift-virtualization
  namespace: default
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: acm/cnv-operator-install
          operator: In
          values:
          - "true"
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: openshift-virtualization
  namespace: default
placementRef:
  name: openshift-virtualization
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
  - name: openshift-virtualization
    kind: Policy
    apiGroup: policy.open-cluster-management.io

---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: openshift-virtualization-mtv
  namespace: default
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: local-cluster
          operator: In
          values:
          - "true"
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: openshift-virtualization-mtv
  namespace: default
placementRef:
  name: openshift-virtualization-mtv
  kind: Placement
  apiGroup: cluster.open-cluster-management.io
subjects:
  - name: openshift-virtualization-mtv
    kind: Policy
    apiGroup: policy.open-cluster-management.io