---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: create-vm-sample
  namespace: default
spec:
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: create-vm-with-rootdisk-and-datadisk
        spec:
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          remediationAction: inform
          severity: low  # Present for console wizard compatibility
          object-templates:
            - complianceType: musthave
              objectDefinition:
                ### Virtual Machine manifest with a root disk and a data disk
                apiVersion: kubevirt.io/v1
                kind: VirtualMachine
                metadata:
                  name: vm02
                  namespace: default
                spec:
                  dataVolumeTemplates:
                    - metadata:
                        creationTimestamp: null
                        name: fedora-vm02
                      spec:
                        sourceRef:
                          kind: DataSource
                          name: fedora
                          namespace: openshift-virtualization-os-images
                        storage:
                          resources:
                            requests:
                              storage: '32212254720'
                          storageClassName: managed-csi
                    - metadata:
                        creationTimestamp: null
                        name: dv-fedora-vm02
                      spec:
                        source:
                          blank: {}
                        storage:
                          resources:
                            requests:
                              storage: 30Gi
                          storageClassName: managed-csi
                  instancetype:
                    kind: virtualmachineclusterinstancetype
                    name: u1.small
                  preference:
                    kind: virtualmachineclusterpreference
                    name: fedora
                  runStrategy: Halted
                  template:
                    metadata:
                      creationTimestamp: null
                      labels:
                        network.kubevirt.io/headlessService: headless
                    spec:
                      architecture: amd64
                      domain:
                        devices:
                          autoattachPodInterface: false
                          disks:
                            - disk:
                                bus: virtio
                              name: disk-vm02
                          interfaces:
                            - masquerade: {}
                              name: default
                        machine:
                          type: pc-q35-rhel9.4.0
                        resources: {}
                      networks:
                        - name: default
                          pod: {}
                      subdomain: headless
                      volumes:
                        - dataVolume:
                            name: fedora-vm02
                          name: rootdisk
                        - cloudInitNoCloud:
                            userData: |
                              #cloud-config
                              chpasswd:
                                expire: false
                              password: change-me-5738
                              user: fedora
                              #ssh_authorized_keys:
                              #  - ssh-rsa ssh-rsa...
                          name: cloudinitdisk
                        - dataVolume:
                            name: dv-fedora-vm02
                          name: disk-vm02

    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: create-vm-with-rootdisk-only
        spec:
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          remediationAction: inform
          severity: low  # Present for console wizard compatibility
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: policy.open-cluster-management.io/v1
                kind: ConfigurationPolicy
                metadata:
                  name: create-vm-with-rootdisk-only
                spec:
                  namespaceSelector:
                    exclude:
                      - kube-*
                    include:
                      - default
                  object-templates:
                    - complianceType: musthave
                      objectDefinition:
                        ### Virtual Machine manifest with a root disk only
                        apiVersion: kubevirt.io/v1
                        kind: VirtualMachine
                        metadata:
                          name: vm01
                          namespace: default
                        spec:
                          dataVolumeTemplates:
                            - metadata:
                                creationTimestamp: null
                                name: fedora-vm01
                              spec:
                                sourceRef:
                                  kind: DataSource
                                  name: fedora
                                  namespace: openshift-virtualization-os-images
                                storage:
                                  resources:
                                    requests:
                                      storage: '32212254720'
                                  storageClassName: managed-csi
                          instancetype:
                            kind: virtualmachineclusterinstancetype
                            name: u1.small
                          preference:
                            kind: virtualmachineclusterpreference
                            name: fedora
                          runStrategy: Halted
                          template:
                            metadata:
                              creationTimestamp: null
                              labels:
                                network.kubevirt.io/headlessService: headless
                            spec:
                              architecture: amd64
                              domain:
                                devices:
                                  autoattachPodInterface: false
                                  interfaces:
                                    - masquerade: {}
                                      name: default
                                machine:
                                  type: pc-q35-rhel9.4.0
                                resources: {}
                              networks:
                                - name: default
                                  pod: {}
                              subdomain: headless
                              volumes:
                                - dataVolume:
                                    name: fedora-vm01
                                  name: rootdisk
                                - cloudInitNoCloud:
                                    userData: |
                                      #cloud-config
                                      chpasswd:
                                        expire: false
                                      password: change-me-5738
                                      user: fedora
                                      #ssh_authorized_keys:
                                      #  - ssh-rsa ssh-rsa...
                                  name: cloudinitdisk
          
# PlacementRule and PlacementBinding
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: create-vm-sample
  namespace: default
spec:
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: "acm/cnv-create-vm-sample"
        operator: In
        values:
          - "true"
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: create-vm-sample
  namespace: default
placementRef:
  name: create-vm-sample
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: create-vm-sample
    kind: Policy
    apiGroup: policy.open-cluster-management.io