apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm02
  namespace: default
spec:
  dataVolumeTemplates:
    - metadata:
        creationTimestamp: null
        name: fedora-vm01
      spec:
        sourceRef:
          kind: DataSource
          name: fedora
          namespace: openshift-virtualization-os-images
        storage:
          resources:
            requests:
              storage: '32212254720'
          storageClassName: managed-csi
    - metadata:
        creationTimestamp: null
        name: dv-fedora-vm01
      spec:
        source:
          blank: {}
        storage:
          resources:
            requests:
              storage: 30Gi
          storageClassName: managed-csi
  instancetype:
    kind: virtualmachineclusterinstancetype
    name: u1.small
  preference:
    kind: virtualmachineclusterpreference
    name: fedora
  runStrategy: Halted
  template:
    metadata:
      creationTimestamp: null
      labels:
        network.kubevirt.io/headlessService: headless
    spec:
      architecture: amd64
      domain:
        devices:
          autoattachPodInterface: false
          disks:
            - disk:
                bus: virtio
              name: disk-vm01
          interfaces:
            - masquerade: {}
              name: default
        machine:
          type: pc-q35-rhel9.4.0
        resources: {}
      networks:
        - name: default
          pod: {}
      subdomain: headless
      volumes:
        - dataVolume:
            name: fedora-vm01
          name: rootdisk
        - cloudInitNoCloud:
            userData: |
              #cloud-config
              chpasswd:
                expire: false
              password: change-me-5738
              user: fedora
              #ssh_authorized_keys:
              #  - ssh-rsa ssh-rsa...
          name: cloudinitdisk
        - dataVolume:
            name: dv-fedora-vm01
          name: disk-vm01
