apiVersion: v1
kind: Namespace
metadata:
  name: openshift-compliance
---
apiVersion: policy.open-cluster-management.io/v1beta1
kind: OperatorPolicy
metadata:
  name: operatorpolicy-comp-operator
spec:
  remediationAction: enforce
  severity: high
  complianceType: musthave
  upgradeApproval: Automatic
  operatorGroup:
    name: compliance-operator
    namespace: openshift-compliance
    targetNamespaces:
      - openshift-compliance
  subscription:
    channel: stable
    name: compliance-operator
    namespace: openshift-compliance
    source: redhat-operators
    sourceNamespace: openshift-marketplace
