# This manifest creates storage nodes necessary for installing OPP on an AWS or VMWare OpenShift cluster.
# - AWS creates 2 replicas in each of 3 zones.
# - VMWare creates 6 replicas
# Review the content of the machine sets to determine if you need to make customizations.
#
# More details on installing OCS including the creation of the MachineSets is located here:
# https://red-hat-storage.github.io/ocs-training/training/ocs4/ocs.html#_scale_ocp_cluster_and_add_new_worker_nodes
#
# This policy contains an Amazon Machine Identifier which must be updated in the policy.  Obtain the AMI id from: 
# https://access.redhat.com/documentation/en-us/openshift_container_platform/4.12/html/installing/installing-on-aws#installation-aws-user-infra-rhcos-ami_installing-aws-user-infra
# AMI IDs are provided in a settings configmap which can be adjusted as desired.
#
apiVersion: policy.open-cluster-management.io/v1
kind: ConfigurationPolicy
metadata:
  name: opp-storage-machinesets
spec:
  remediationAction: enforce
  severity: low
  object-templates-raw: |
    {{- if (eq (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").spec.platformSpec.type "AWS") }}
      {{- range $i, $zone := list "a" "b" "c" }}
    - complianceType: musthave
      objectDefinition:
        apiVersion: machine.openshift.io/v1beta1
        kind: MachineSet
        metadata:
          labels:
            machine.openshift.io/cluster-api-cluster: '{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}'
            machine.openshift.io/cluster-api-machine-role: workerocs
            machine.openshift.io/cluster-api-machine-type: workerocs
          name: {{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}-workerocs-{{ list (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.platformStatus.aws.region $zone | join "" }}
          namespace: openshift-machine-api
        spec:
          replicas: '{{ fromConfigMap "policies" "opp-settings" "awsReplicas" | toInt }}'
          selector:
            matchLabels:
              machine.openshift.io/cluster-api-cluster: '{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}'
              machine.openshift.io/cluster-api-machineset: {{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}-workerocs-{{ list (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.platformStatus.aws.region $zone | join "" }}
          template:
            metadata:
              labels:
                machine.openshift.io/cluster-api-cluster: '{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}'
                machine.openshift.io/cluster-api-machine-role: workerocs
                machine.openshift.io/cluster-api-machine-type: workerocs
                machine.openshift.io/cluster-api-machineset: {{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}-workerocs-{{ list (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.platformStatus.aws.region $zone | join "" }}
            spec:
              metadata:
                labels:
                  cluster.ocs.openshift.io/openshift-storage: ""
                  node-role.kubernetes.io/worker: ""
              providerSpec:
                value:
                  ami:
                    id: '{{ fromConfigMap "policies" "opp-settings" (printf "%s-%s" (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.platformStatus.aws.region (fromClusterClaim "openshiftversion-major-minor")) }}'
                  apiVersion: awsproviderconfig.openshift.io/v1beta1
                  blockDevices:
                  - ebs:
                      iops: 0
                      volumeSize: 120
                      volumeType: gp3
                  credentialsSecret:
                    name: aws-cloud-credentials
                  deviceIndex: 0
                  iamInstanceProfile:
                    id: '{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}-worker-profile'
                  instanceType: '{{ fromConfigMap "policies" "opp-settings" "awsInstanceType" }}'
                  kind: AWSMachineProviderConfig
                  metadata:
                    creationTimestamp: null
                  placement:
                    availabilityZone: {{ list (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.platformStatus.aws.region $zone | join "" }}
                    region: '{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.platformStatus.aws.region }}'
                  publicIp: null
                  securityGroups:
                  - filters:
                    - name: tag:Name
                      values:
                      - '{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}-worker-sg'
                  {{- $ocpversion := semver (fromClusterClaim "version.openshift.io") }}
                  {{- if gt $ocpversion.Minor 15 }}
                  - filters:
                    - name: tag:Name
                      values:
                      - '{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}-node'
                  - filters:
                    - name: tag:Name
                      values:
                      - '{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}-lb'
                  {{- end }}
                  subnet:
                    filters:
                    - name: tag:Name
                      values:
                      - {{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}-private-{{ list (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.platformStatus.aws.region $zone | join "" }}
                  tags:
                  - name: 'kubernetes.io/cluster/{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}'
                    value: owned
                  userDataSecret:
                    name: worker-user-data
      {{- end }}
    {{- else }}
    - complianceType: musthave
      objectDefinition:
        apiVersion: machine.openshift.io/v1beta1
        kind: MachineSet
        metadata:
          annotations:
            machine.openshift.io/memoryMb: '{{ fromConfigMap "policies" "opp-settings" "vmwareMemory" }}'
            machine.openshift.io/vCPU: '{{ fromConfigMap "policies" "opp-settings" "vmwareCPU" }}'
          labels:
            machine.openshift.io/cluster-api-cluster: {{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}
          name: {{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}-storage
          namespace: openshift-machine-api
        spec:
          replicas: '{{ fromConfigMap "policies" "opp-settings" "vmwareReplicas" | toInt }}'
          selector:
            matchLabels:
              machine.openshift.io/cluster-api-cluster: {{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}
              machine.openshift.io/cluster-api-machineset: {{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}-storage
          template:
            metadata:
              labels:
                machine.openshift.io/cluster-api-cluster: {{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}
                machine.openshift.io/cluster-api-machine-role: storage
                machine.openshift.io/cluster-api-machine-type: storage
                machine.openshift.io/cluster-api-machineset: {{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}-storage
            spec:
              lifecycleHooks: {}
              metadata:
                labels:
                  cluster.ocs.openshift.io/openshift-storage: ""
              providerSpec:
                value:
                  apiVersion: machine.openshift.io/v1beta1
                  credentialsSecret:
                    name: vsphere-cloud-credentials
                  diskGiB: 120
                  kind: VSphereMachineProviderSpec
                  memoryMiB: '{{ fromConfigMap "policies" "opp-settings" "vmwareMemory" | toInt }}'
                  metadata:
                    creationTimestamp: null
                  network:
                    devices:
                    - networkName: {{ (index (index (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").spec.platformSpec.vsphere.failureDomains 0).topology.networks 0) }}
                  numCPUs: '{{ fromConfigMap "policies" "opp-settings" "vmwareCPU" | toInt }}'
                  numCoresPerSocket: 4
                  snapshot: ""
                  template: {{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}-rhcos-generated-region-generated-zone
                  userDataSecret:
                    name: worker-user-data
                  workspace:
                    datacenter: {{ (index (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").spec.platformSpec.vsphere.failureDomains 0).topology.datacenter }}
                    datastore: {{ (index (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").spec.platformSpec.vsphere.failureDomains 0).topology.datastore }}
                    folder: /{{ (index (index (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").spec.platformSpec.vsphere.vcenters 0).datacenters 0) }}/vm/{{ (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").status.infrastructureName }}
                    resourcePool: {{ (index (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").spec.platformSpec.vsphere.failureDomains 0).topology.resourcePool }}
                    server: {{ (index (lookup "config.openshift.io/v1" "Infrastructure" "" "cluster").spec.platformSpec.vsphere.vcenters 0).server }}
    {{- end }}
